language: php
sudo: required
# hack of https://github.com/wmde/WikidataBuildResources/blob/master/.travis.yml

php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
#  - "7.0"
  - "hhvm"

env:
  matrix:
# As new versions of mediawiki are released they should be added to the matrix
    - MW=master DBTYPE=mysql

before_script:
  - set -x
  - if [ ${php:0:1} == "7" ];
    then phpunitname='phpunit'; else
    phpunitname='phpunit-old';
    fi
  - wget https://phar.phpunit.de/$phpunitname.phar
  - chmod +x phpunit-old.phar
  - mv phpunit-old.phar Reservation/phpunit.phar
  - originalDirectory=$(pwd)
  - cd ..
  - wget https://github.com/wikimedia/mediawiki/archive/$MW.tar.gz
  - tar -zxf ${MW}.tar.gz
  - mv mediawiki-${MW} mediawiki-core
  - cd mediawiki-core
#  - composer self-update
  - composer install --no-dev
  - mysql -e 'create database my_wiki;'
#  - mysql -e "grant all privileges on *.* to 'wikiuser'@'localhost';"

  - php maintenance/install.php --dbtype ${DBTYPE} --dbuser root --dbname my_wiki WikiName admin --pass adminPass
  - cd extensions
  - cp -r ${originalDirectory}/Reservation Reservation
  - cd Reservation
  - mysql -u root my_wiki < table.sql
  - mysql -u root my_wiki -e "SELECT res_resource_name FROM res_resource;"
  - mysql -u root my_wiki -e "SELECT res_group_right FROM res_group;"
  - cd ../../


  - echo '$wgDBtype = "mysql";' >> LocalSettings.php
  - echo '$wgDBuser = "root";' >> LocalSettings.php
  - echo '$wgDBserver = "localhost";' >> LocalSettings.php
  - echo '$wgDBname = "my_wiki";' >> LocalSettings.php
  - echo 'error_reporting(E_ALL| E_STRICT);' >> LocalSettings.php
  - echo 'ini_set("display_errors", 1);' >> LocalSettings.php
  - echo '$wgShowExceptionDetails = true;' >> LocalSettings.php
  - echo '$wgDevelopmentWarnings = true;' >> LocalSettings.php
  - echo '$wgLanguageCode = "'en'";' >> LocalSettings.php
  
  - echo "wfLoadExtension( 'Reservation' );" >> LocalSettings.php
  - php maintenance/update.php

script:
  - set -x
  - cd ../mediawiki-core/
  - php tests/phpunit/phpunit.php --with-phpunitdir extensions/Reservation --configuration extensions/Reservation/suite.extensions.xml
