language: php
sudo: required
# hack of https://github.com/wmde/WikidataBuildResources/blob/master/.travis.yml

php:
  - "5.6"
  - "7.0"
  - "hhvm"
  - "nightly"

env:
  matrix:
# As new versions of mediawiki are released they should be added to the matrix
    - MW=master DBTYPE=mysql

before_script:
  - set -x
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
  - mv phpunit.phar Reservation/
  - originalDirectory=$(pwd)
  - cd ..
  - wget https://github.com/wikimedia/mediawiki/archive/$MW.tar.gz
  - tar -zxf ${MW}.tar.gz
  - mv mediawiki-${MW} mediawiki-core
  - cd mediawiki-core
#  - composer self-update
  - composer install --no-dev
  - mysql -e 'create database myapp_test;'
  - mysql myapp_test -e 'show tables;'

  - php maintenance/install.php --dbtype ${DBTYPE} --dbuser root --dbname myapp_test WikiName admin --pass adminPass
  - mysql myapp_test -e 'show tables;'
  - cd extensions
  - cp -r ${originalDirectory}/Reservation Reservation
  - cd ..


  - echo '$wgDBtype = "mysql";' >> LocalSettings.php
  - echo '$wgDBuser = "root";' >> LocalSettings.php
  - echo '$wgDBserver = "localhost";' >> LocalSettings.php
  - echo '$wgDBname = "myapp_test";' >> LocalSettings.php
  - echo 'error_reporting(E_ALL| E_STRICT);' >> LocalSettings.php
  - echo 'ini_set("display_errors", 1);' >> LocalSettings.php
  - echo '$wgShowExceptionDetails = true;' >> LocalSettings.php
  - echo '$wgDevelopmentWarnings = true;' >> LocalSettings.php
  - echo '$wgLanguageCode = "'en'";' >> LocalSettings.php
  
  - echo "wfLoadExtension( 'Reservation' );" >> LocalSettings.php
  - php maintenance/update.php

script:
  - set -x
  - cd ../mediawiki-core/
  - php tests/phpunit/phpunit.php --with-phpunitdir extensions/Reservation --configuration extensions/Reservation/suite.extensions.xml
